# lightning.pytorch==2.0.0
seed_everything: true
trainer:
  accelerator: auto
  default_root_dir: artifacts
  # resume_from_checkpoint: null # reload the model
  max_epochs: 2
  accumulate_grad_batches: 1
  log_every_n_steps: 1
  enable_checkpointing: true
  # strategy: single_device
  # profiler: simple
  # strategy: deepspeed_stage_3_offload
  devices: auto
  num_nodes: 1
  precision: 16
  logger: null
  callbacks: null
  fast_dev_run: false
  min_epochs: null
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  enable_progress_bar: null
  enable_model_summary: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  # use_distributed_sampler: false
  detect_anomaly: false
  # barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
model:
  T_0: 10000000
  T_mult: 2
  learning_rate: 5.0e-04
  lora: false
  base_model:
    class_path: model.Gpt2
    init_args:
      from_pretrained: true
data: 
  local: true
  dataset_name: gpt2_alpaca_data_cleaned
  batch_size_train: 5
  subset_train: 10
  workers: 2






























































































































































































































































































































































































































































































